### ISSUE TITLE
Why block syntax needed for options?

### ISSUE THREAD

**Issue by ziy** [oaqa/uima-ecd#17]
Why do we need to put a vertical bar to make the options as a block? For example,

```
pipeline:
  - inherit: ecd.phase
    name: keyterm-expansion
    options: |
      - inherit: helloqa.keyterm.simple
```

It might be more intuitive to have the value type for the key "options" as a list (aka an Iterable), so that parameter value can be flattened to higher layers, and we will be one step closer to present the "effective yaml description".

```
pipeline:
  - inherit: ecd.phase
    name: keyterm-expansion
    options:
      - inherit: helloqa.keyterm.simple
        param: value
```
